version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kavvadias/leraport
    ports:
      - 5000:5000
    volumes:
      - ./:/lera-flask
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 33067:3306
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=leraport
      - POSTGRES_PASSWORD=leraport
      - POSTGRES_DB=leraport

volumes:
  postgres_data:
