"""photos table

Revision ID: 0822269e7d28
Revises: 
Create Date: 2021-05-20 15:19:22.057748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0822269e7d28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('album', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_album'), 'photo', ['album'], unique=True)
    op.create_index(op.f('ix_photo_timestamp'), 'photo', ['timestamp'], unique=False)
    op.create_index(op.f('ix_photo_title'), 'photo', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_title'), table_name='photo')
    op.drop_index(op.f('ix_photo_timestamp'), table_name='photo')
    op.drop_index(op.f('ix_photo_album'), table_name='photo')
    op.drop_table('photo')
    # ### end Alembic commands ###
