"""img_url deleted

Revision ID: 7efad811933e
Revises: dfd11f5ac2e7
Create Date: 2021-05-30 12:44:42.134008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7efad811933e'
down_revision = 'dfd11f5ac2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photo_img_url', table_name='photo')
    op.drop_column('photo', 'img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('img_url', sa.VARCHAR(length=420), nullable=True))
    op.create_index('ix_photo_img_url', 'photo', ['img_url'], unique=False)
    # ### end Alembic commands ###
