"""Photo population

Revision ID: dfd11f5ac2e7
Revises: e3580c675e4e
Create Date: 2021-05-28 14:39:55.636926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd11f5ac2e7'
down_revision = 'e3580c675e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photo_album', table_name='photo')
    op.create_index(op.f('ix_photo_album'), 'photo', ['album'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_album'), table_name='photo')
    op.create_index('ix_photo_album', 'photo', ['album'], unique=False)
    # ### end Alembic commands ###
