"""empty message

Revision ID: e3580c675e4e
Revises: 0822269e7d28
Create Date: 2021-05-21 18:48:29.370689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3580c675e4e'
down_revision = '0822269e7d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('img_url', sa.String(length=420), nullable=True))
    op.create_index(op.f('ix_photo_img_url'), 'photo', ['img_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_img_url'), table_name='photo')
    op.drop_column('photo', 'img_url')
    # ### end Alembic commands ###
